// <auto-generated />
using System;
using EmprestimoLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmprestimoLibrary.Migrations
{
    [DbContext(typeof(ControleEmprestimoLivroContext))]
    [Migration("20260926042344_AddIsEmprestimoToLivro")]
    partial class AddIsEmprestimoToLivro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmprestimoLibrary.Models.Carteira", b =>
                {
                    b.Property<int>("IdCarteira")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_carteira");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarteira"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("EditoraIdEditora")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdEditora")
                        .HasColumnType("int")
                        .HasColumnName("id_editora");

                    b.Property<decimal>("SaldoCarteira")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("saldo_carteira");

                    b.HasKey("IdCarteira");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("EditoraIdEditora");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasFilter("[id_cliente] IS NOT NULL");

                    b.HasIndex("IdEditora")
                        .IsUnique()
                        .HasFilter("[id_editora] IS NOT NULL");

                    b.ToTable("Carteiras", null, t =>
                        {
                            t.HasCheckConstraint("CK_Carteira_Dono", "(id_cliente IS NOT NULL AND id_editora IS NULL) OR (id_cliente IS NULL AND id_editora IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("CpfCliente")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("cpf_cliente");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email_cliente");

                    b.Property<string>("EnderecoCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("endereco_cliente");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("SenhaCliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senha_cliente");

                    b.Property<bool>("SituacaoConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("situacao_conta");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("telefone_cliente");

                    b.HasKey("IdCliente");

                    b.HasIndex("EmailCliente")
                        .IsUnique();

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<int>("CompraQuantidade")
                        .HasColumnType("int")
                        .HasColumnName("compra_quantidade");

                    b.Property<decimal>("CompraValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("compra_valor_total");

                    b.Property<decimal>("CompraValorUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("compra_valor_unitario");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_compra");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("id_livro");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdLivro");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Editora", b =>
                {
                    b.Property<int>("IdEditora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_editora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEditora"));

                    b.Property<string>("EmailEditora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email_editora");

                    b.Property<string>("NomeEditora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_editora");

                    b.Property<string>("SenhaEditora")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senha_editora");

                    b.HasKey("IdEditora");

                    b.HasIndex("EmailEditora")
                        .IsUnique();

                    b.ToTable("Editoras", (string)null);
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Emprestimo", b =>
                {
                    b.Property<int>("IdEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_emprestimo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmprestimo"));

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime2")
                        .HasColumnName("lce_dataDevolucao");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime2")
                        .HasColumnName("lce_dataEmprestimo");

                    b.Property<DateTime>("DataPrevistaDevolucao")
                        .HasColumnType("datetime2")
                        .HasColumnName("lce_dataPrevistaDevolucao");

                    b.Property<bool>("Devolvido")
                        .HasColumnType("bit")
                        .HasColumnName("lce_devolvido");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("lce_id_cliente");

                    b.Property<int>("IdLivro")
                        .HasColumnType("int")
                        .HasColumnName("lce_id_livro");

                    b.Property<bool>("MultaDescontada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("lce_multaDescontada");

                    b.Property<decimal?>("ValorMulta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("lce_valorMulta");

                    b.HasKey("IdEmprestimo");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdLivro");

                    b.ToTable("LIVRO_CLIENTE_EMPRESTIMO", (string)null);
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Livro", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_livro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLivro"));

                    b.Property<int?>("EditoraIdEditora")
                        .HasColumnType("int");

                    b.Property<int>("IdEditora")
                        .HasColumnType("int")
                        .HasColumnName("id_editora");

                    b.Property<bool>("IsEmprestavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_emprestavel");

                    b.Property<string>("LivroAutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("livro_autor");

                    b.Property<string>("LivroEdicao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("livro_edicao");

                    b.Property<string>("LivroEditora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("livro_editora");

                    b.Property<decimal>("LivroPreco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("livro_preco");

                    b.Property<int>("LivroQuantidade")
                        .HasColumnType("int")
                        .HasColumnName("livro_quantidade");

                    b.Property<string>("LivroTitulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("livro_titulo");

                    b.Property<string>("SituacaoLivro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasDefaultValue("D")
                        .HasColumnName("situacao_livro");

                    b.HasKey("IdLivro");

                    b.HasIndex("EditoraIdEditora");

                    b.HasIndex("IdEditora");

                    b.ToTable("Livros", (string)null);
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.MovimentacaoCarteira", b =>
                {
                    b.Property<int>("IdMovimentacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimentacao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimentacao"));

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_movimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdCarteira")
                        .HasColumnType("int")
                        .HasColumnName("id_carteira");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_movimento");

                    b.Property<decimal>("ValorMovimento")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_movimento");

                    b.HasKey("IdMovimentacao");

                    b.HasIndex("IdCarteira");

                    b.ToTable("MovimentacoesCarteira", (string)null);
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Carteira", b =>
                {
                    b.HasOne("EmprestimoLibrary.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("EmprestimoLibrary.Models.Editora", "Editora")
                        .WithMany()
                        .HasForeignKey("EditoraIdEditora");

                    b.HasOne("EmprestimoLibrary.Models.Cliente", null)
                        .WithOne("Carteira")
                        .HasForeignKey("EmprestimoLibrary.Models.Carteira", "IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EmprestimoLibrary.Models.Editora", null)
                        .WithOne("Carteira")
                        .HasForeignKey("EmprestimoLibrary.Models.Carteira", "IdEditora")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("Editora");
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Compra", b =>
                {
                    b.HasOne("EmprestimoLibrary.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmprestimoLibrary.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Emprestimo", b =>
                {
                    b.HasOne("EmprestimoLibrary.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EmprestimoLibrary.Models.Livro", null)
                        .WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Livro", b =>
                {
                    b.HasOne("EmprestimoLibrary.Models.Editora", "Editora")
                        .WithMany()
                        .HasForeignKey("EditoraIdEditora");

                    b.HasOne("EmprestimoLibrary.Models.Editora", null)
                        .WithMany()
                        .HasForeignKey("IdEditora")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Editora");
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.MovimentacaoCarteira", b =>
                {
                    b.HasOne("EmprestimoLibrary.Models.Carteira", null)
                        .WithMany("Movimentacoes")
                        .HasForeignKey("IdCarteira")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Carteira", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Cliente", b =>
                {
                    b.Navigation("Carteira");
                });

            modelBuilder.Entity("EmprestimoLibrary.Models.Editora", b =>
                {
                    b.Navigation("Carteira");
                });
#pragma warning restore 612, 618
        }
    }
}
